name: Continuous Deployment
 
on: 
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: login to Heroku Container
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login
    - name: Build and push, then release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
        heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web